/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nhisyamj.clinic.api;

import com.nhisyamj.clinic.model.Staff;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

/**
 *<h1>StaffApi</h1>
 * Class description
 * <p>
 ***
 * @author: Hisyam Johan
 * @since: 16/08/2018
 * @version: 1.0
 * Time: 10:50 PM
 * Email: nhisyamj@gmail.com
 ***
 */
@Api(value = "staff", description = "the staff API")
public interface StaffApi {

    @ApiOperation(value = "Add staff", nickname = "addStaff", notes = "Adding staff", tags={ "staff", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created") })
    @RequestMapping(value = "/staff",
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addStaff(@ApiParam(value = "staff details need to be added"  )  @Valid @RequestBody Staff body);


    @ApiOperation(value = "Get list of staff", nickname = "getStaff", notes = "get list of staff and details", response = Staff.class, responseContainer = "List", tags={ "staff", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Staff.class, responseContainer = "List") })
    @RequestMapping(value = "/staff",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Staff>> getStaff();


    @ApiOperation(value = "Get list of staff find by type", nickname = "staffFindByTypeGet", notes = "Get list of staff find type", response = Staff.class, responseContainer = "List", tags={ "staff", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Staff.class, responseContainer = "List") })
    @RequestMapping(value = "/staff/findByType",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Staff>> staffFindByTypeGet(@ApiParam(value = "") @Valid @RequestParam(value = "staffName", required = false) String staffName,@ApiParam(value = "") @Valid @RequestParam(value = "staffId", required = false) Long staffId);


    @ApiOperation(value = "Update staff", nickname = "updateStaff", notes = "update staff detail", tags={ "staff", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No Content") })
    @RequestMapping(value = "/staff",
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateStaff(@ApiParam(value = "staff details need to be updated"  )  @Valid @RequestBody Staff body);

}
